# fly.toml app configuration file generated for shipany-bot-in-telegram on 2024-06-04T21:56:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shipany-bot-in-telegram'
primary_region = 'cdg'

[build]

[processes]
worker = "-m shipany.bot.cli.main run conversation.json"

[http_service]
processes = ["worker"]
internal_port = 8000
force_https = true
auto_stop_machines = false

[[http_service.checks]]
grace_period = "10s"
interval = "60s"
method = "GET"
timeout = "5s"
path = "/"

[env]
WEB_SERVER_HOST = "0.0.0.0"
WEB_SERVER_PORT = "8000"

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
